name: Build Windows Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Pillow
        
    - name: Python GUI With TkInter
      uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: resize.py
        onefile: true
        enable-plugins: tk-inter

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: exe
        path: build/resize.exe