name: Build and Release Windows Executable

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Pillow nuitka

    - name: Build executable with PyInstaller and UPX
      run: |
        python -m nuitka --mingw64 resize.py

    - name: Get Tag Name
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      shell: bash

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./resize.exe"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.TAG_NAME }}
        name: Release ${{ env.TAG_NAME }}
        draft: false
        prerelease: false
        generateReleaseNotes: true
